# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'authForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(350, 400)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 350, 400))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.exitBtn = QtWidgets.QPushButton(self.frame)
        self.exitBtn.setGeometry(QtCore.QRect(50, 330, 250, 40))
        self.exitBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.exitBtn.setAutoDefault(False)
        self.exitBtn.setObjectName("exitBtn")
        self.loginBtn = QtWidgets.QPushButton(self.frame)
        self.loginBtn.setGeometry(QtCore.QRect(50, 280, 250, 40))
        self.loginBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.loginBtn.setObjectName("loginBtn")
        self.passwordEdit = QtWidgets.QLineEdit(self.frame)
        self.passwordEdit.setGeometry(QtCore.QRect(50, 200, 250, 30))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        self.passwordEdit.setFont(font)
        self.passwordEdit.setText("")
        self.passwordEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordEdit.setObjectName("passwordEdit")
        self.emailCombo = QtWidgets.QComboBox(self.frame)
        self.emailCombo.setGeometry(QtCore.QRect(50, 110, 250, 30))
        self.emailCombo.setObjectName("emailCombo")
        self.emailCombo.addItem("")
        self.emailCombo.addItem("")
        self.emailCombo.addItem("")
        self.logoLabel = QtWidgets.QLabel(self.frame)
        self.logoLabel.setGeometry(QtCore.QRect(20, 20, 311, 41))
        self.logoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.logoLabel.setObjectName("logoLabel")
        self.loginEdit = QtWidgets.QLineEdit(self.frame)
        self.loginEdit.setGeometry(QtCore.QRect(50, 160, 250, 30))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        self.loginEdit.setFont(font)
        self.loginEdit.setText("")
        self.loginEdit.setObjectName("loginEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.exitBtn.setText(_translate("Dialog", "Выход/назад"))
        self.loginBtn.setText(_translate("Dialog", "Войти"))
        self.passwordEdit.setPlaceholderText(_translate("Dialog", "password"))
        self.emailCombo.setItemText(0, _translate("Dialog", "yandex"))
        self.emailCombo.setItemText(1, _translate("Dialog", "google"))
        self.emailCombo.setItemText(2, _translate("Dialog", "mail.ru"))
        self.logoLabel.setText(_translate("Dialog", "CPIS"))
        self.loginEdit.setPlaceholderText(_translate("Dialog", "login"))
